// Auto-generated by rtttl2pcm.py
#pragma once

#include "tone_positive.h"
#include "tone_warning.h"
#include "tone_error.h"
#include "tone_info.h"
#include "tone_welcome.h"

enum class EventTone {
    reminder_fired,
    battery_low,
    reminders_syncing,
    welcome_back,
    server_down,
    server_ok,
    dfu_started,
    dfu_complete,
    dfu_failed,
    watch_paired,
    reminder_ackd,
};

struct ToneData {
    const uint8_t* data;
    size_t len;
};

inline ToneData get_event_tone(EventTone event) {
    switch (event) {
        case EventTone::reminder_fired: return {tone_warning, tone_warning_len};
        case EventTone::battery_low: return {tone_warning, tone_warning_len};
        case EventTone::reminders_syncing: return {tone_info, tone_info_len};
        case EventTone::welcome_back: return {tone_welcome, tone_welcome_len};
        case EventTone::server_down: return {tone_error, tone_error_len};
        case EventTone::server_ok: return {tone_positive, tone_positive_len};
        case EventTone::dfu_started: return {tone_info, tone_info_len};
        case EventTone::dfu_complete: return {tone_positive, tone_positive_len};
        case EventTone::dfu_failed: return {tone_error, tone_error_len};
        case EventTone::watch_paired: return {tone_positive, tone_positive_len};
        case EventTone::reminder_ackd: return {tone_info, tone_info_len};
        default: return {tone_positive, tone_positive_len};
    }
}
