#!/usr/bin/env python3
"""Convert RTTTL ringtones to raw PCM and C header arrays.

Usage:
    python3 rtttl2pcm.py              # Generate all tones
    python3 rtttl2pcm.py --preview    # Play through speakers (requires sounddevice)
"""

import struct
import math
import os
import sys

SAMPLE_RATE = 16000
BITS = 16
CHANNELS = 1

# Note frequencies (octave 4)
NOTE_FREQS = {
    'c': 261.63, 'c#': 277.18, 'd': 293.66, 'd#': 311.13,
    'e': 329.63, 'f': 349.23, 'f#': 369.99, 'g': 392.00,
    'g#': 415.30, 'a': 440.00, 'a#': 466.16, 'b': 493.88,
    'p': 0,  # pause
}


def parse_rtttl(rtttl_str):
    """Parse RTTTL string into (name, notes) where notes are (freq_hz, duration_ms)."""
    parts = rtttl_str.strip().split(':')
    name = parts[0].strip()

    # Parse defaults
    defaults = {}
    for item in parts[1].strip().split(','):
        k, v = item.strip().split('=')
        defaults[k.strip().lower()] = int(v.strip())

    default_dur = defaults.get('d', 4)
    default_oct = defaults.get('o', 6)
    bpm = defaults.get('b', 63)

    # Whole note duration in ms
    whole_note_ms = (60000.0 / bpm) * 4

    notes = []
    for token in parts[2].strip().split(','):
        token = token.strip().lower()
        if not token:
            continue

        # Parse duration prefix
        i = 0
        dur_str = ''
        while i < len(token) and token[i].isdigit():
            dur_str += token[i]
            i += 1
        duration = int(dur_str) if dur_str else default_dur

        # Parse note name
        note_name = ''
        if i < len(token):
            note_name += token[i]
            i += 1
        if i < len(token) and token[i] == '#':
            note_name += '#'
            i += 1

        # Check for dot (1.5x duration)
        dotted = False
        if i < len(token) and token[i] == '.':
            dotted = True
            i += 1

        # Parse octave suffix
        oct_str = ''
        while i < len(token) and token[i].isdigit():
            oct_str += token[i]
            i += 1
        octave = int(oct_str) if oct_str else default_oct

        # Calculate frequency
        if note_name == 'p' or note_name == '':
            freq = 0
        else:
            base_freq = NOTE_FREQS.get(note_name, 0)
            freq = base_freq * (2 ** (octave - 4))

        # Calculate duration in ms
        dur_ms = whole_note_ms / duration
        if dotted:
            dur_ms *= 1.5

        notes.append((freq, dur_ms))

    return name, notes


def synthesize(notes, sample_rate=SAMPLE_RATE, fade_ms=5):
    """Generate PCM samples from parsed notes. Returns list of int16 samples."""
    samples = []
    for freq, dur_ms in notes:
        n_samples = int(sample_rate * dur_ms / 1000)
        fade_samples = int(sample_rate * fade_ms / 1000)

        for i in range(n_samples):
            if freq == 0:
                val = 0
            else:
                # Sine wave with envelope
                t = i / sample_rate
                envelope = 1.0
                # Fade in
                if i < fade_samples:
                    envelope = i / fade_samples
                # Fade out
                elif i > n_samples - fade_samples:
                    envelope = (n_samples - i) / fade_samples
                val = int(24000 * envelope * math.sin(2 * math.pi * freq * t))
                val = max(-32768, min(32767, val))
            samples.append(val)
    return samples


def samples_to_raw(samples):
    """Convert int16 samples to raw bytes (little-endian)."""
    return struct.pack(f'<{len(samples)}h', *samples)


def raw_to_c_array(raw_bytes, var_name):
    """Convert raw bytes to C header with uint8_t array."""
    lines = [f'// Auto-generated by rtttl2pcm.py — {SAMPLE_RATE}Hz 16-bit mono PCM']
    lines.append(f'#pragma once')
    lines.append(f'#include <cstdint>')
    lines.append(f'#include <cstddef>')
    lines.append(f'')
    lines.append(f'static const uint8_t {var_name}[] = {{')

    for i in range(0, len(raw_bytes), 16):
        chunk = raw_bytes[i:i+16]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'    {hex_vals},')

    lines.append(f'}};')
    lines.append(f'static const size_t {var_name}_len = sizeof({var_name});')
    lines.append(f'')
    return '\n'.join(lines)


# Event tones — RTTTL format
TONES = {
    # Pleasant ascending chime for positive events
    'tone_positive': 'pos:d=16,o=6,b=200:e,g,b',
    # Descending for warnings
    'tone_warning': 'warn:d=8,o=5,b=160:a,f,d',
    # Urgent repeated for errors
    'tone_error': 'err:d=16,o=6,b=300:c,p,c,p,c',
    # Single soft ding for info
    'tone_info': 'info:d=8,o=6,b=180:e',
    # Welcome home jingle
    'tone_welcome': 'wel:d=16,o=6,b=180:c,e,g,8c7',
}

# Map events to tones
EVENT_TONES = {
    'reminder_fired':    'tone_warning',   # #1  attention
    'battery_low':       'tone_warning',   # #2  attention
    'reminders_syncing': 'tone_info',      # #3  info
    'welcome_back':      'tone_welcome',   # #4  positive
    'server_down':       'tone_error',     # #9  error
    'server_ok':         'tone_positive',  # #10 positive
    'dfu_started':       'tone_info',      # #11 info
    'dfu_complete':      'tone_positive',  # #12 positive
    'dfu_failed':        'tone_error',     # #13 error
    'watch_paired':      'tone_positive',  # #14 positive
    'reminder_ackd':     'tone_info',      # #15 info
}


def main():
    out_dir = os.path.join(os.path.dirname(__file__), '..', 'esphome', 'components', 'pinetime_bridge', 'tones')
    os.makedirs(out_dir, exist_ok=True)

    preview = '--preview' in sys.argv

    print(f'Generating tones at {SAMPLE_RATE}Hz 16-bit mono:')
    for var_name, rtttl_str in TONES.items():
        name, notes = parse_rtttl(rtttl_str)
        samples = synthesize(notes)
        raw = samples_to_raw(samples)

        # Write raw file
        raw_path = os.path.join(out_dir, f'{var_name}.raw')
        with open(raw_path, 'wb') as f:
            f.write(raw)

        # Write C header
        h_path = os.path.join(out_dir, f'{var_name}.h')
        with open(h_path, 'w') as f:
            f.write(raw_to_c_array(raw, var_name))

        dur_ms = sum(d for _, d in notes)
        print(f'  {var_name}: {len(notes)} notes, {dur_ms:.0f}ms, {len(raw)} bytes')

        if preview:
            try:
                import sounddevice as sd
                import numpy as np
                audio = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
                sd.play(audio, SAMPLE_RATE)
                sd.wait()
            except ImportError:
                print('    (install sounddevice for preview)')

    # Write event mapping header
    mapping_path = os.path.join(out_dir, 'event_tones.h')
    with open(mapping_path, 'w') as f:
        f.write('// Auto-generated by rtttl2pcm.py\n')
        f.write('#pragma once\n\n')
        for h_name in TONES:
            f.write(f'#include "{h_name}.h"\n')
        f.write('\n')
        f.write('enum class EventTone {\n')
        for i, name in enumerate(EVENT_TONES):
            f.write(f'    {name},\n')
        f.write('};\n\n')
        f.write('struct ToneData {\n')
        f.write('    const uint8_t* data;\n')
        f.write('    size_t len;\n')
        f.write('};\n\n')
        f.write('inline ToneData get_event_tone(EventTone event) {\n')
        f.write('    switch (event) {\n')
        for event_name, tone_name in EVENT_TONES.items():
            f.write(f'        case EventTone::{event_name}: return {{{tone_name}, {tone_name}_len}};\n')
        f.write(f'        default: return {{{list(TONES.keys())[0]}, {list(TONES.keys())[0]}_len}};\n')
        f.write('    }\n')
        f.write('}\n')

    print(f'\nGenerated {len(TONES)} tones, {len(EVENT_TONES)} event mappings')
    print(f'Output: {out_dir}/')


if __name__ == '__main__':
    main()
